language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran --run-donttest"
    - _R_CHECK_TIMINGS_="0"
